CAT-932: Also build sftp image in Circle

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -162,6 +162,43 @@ jobs:
             docker push ${REPO}/${IMAGE_NAME}:${VTAG} && echo "Pushed successfully 1/2 ${REPO}/${IMAGE_NAME}:${VTAG}" || echo "Failed to push '${VTAG}'"
             docker tag ${IMAGE_NAME}:${VTAG} ${REPO}/${IMAGE_NAME}:${LT}
             docker push ${REPO}/${IMAGE_NAME}:${LT} && echo "Pushed successfully 2/2 ${REPO}/${IMAGE_NAME}:${LT}" || echo "Failed to push '${LT}'"
+  build_sftp:
+    docker:
+      - image: google/cloud-sdk
+    working_directory: ~/repo
+    steps:
+      - run:
+          name: Store Service Account
+          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
+      - run:
+          name: Init Gcloud
+          command: |
+            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
+            gcloud auth configure-docker
+            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
+      - setup_remote_docker
+      - checkout
+      - run:
+          name: Add version and commit sha to build
+          # Note the first command uses a single > to overwrite version.rb completely. Important.
+          command: |
+            echo "ENV['BBB_CI_VERSION'] = '$CIRCLE_BRANCH:$CIRCLE_BUILD_NUM'" > config/initializers/ci_version.rb
+            echo "ENV['BBB_COMMIT_SHA'] = '$CIRCLE_SHA1'" >> config/initializers/ci_version.rb
+            echo "ENV['CIRCLE_COMPARE_URL'] = '$CIRCLE_COMPARE_URL'" >> config/initializers/ci_version.rb
+      - run:
+          name: Build image and push to GCR
+          command: |
+            GCR_HOST=us.gcr.io
+            DOCKER_IMAGE_NAME=$(echo -n ${CIRCLE_PROJECT_REPONAME} | tr '[:upper:]' '[:lower:]'| sed -e 's/_/-/g' -e 's/[^a-z0-9\-]//g')
+
+            REPO="${GCR_HOST}/${GOOGLE_PROJECT_ID}"
+            LT="zzz-not-latest"
+            IMAGE_NAME="item-indexer-sftp"
+
+            docker build --tag "${IMAGE_NAME}:${LT}" -f Dockerfile.sftp . && \
+            docker tag "${IMAGE_NAME}:${LT}" "${REPO}/${IMAGE_NAME}:${LT}" && \
+            docker push "${REPO}/${IMAGE_NAME}:${LT}" && \
+            echo "Pushed successfully ${REPO}/${IMAGE_NAME}:${LT}" || echo "Failed to push '${REPO}/${IMAGE_NAME}:${LT}'"
 workflows:
   version: 2
   ci_workflow:
@@ -171,6 +208,13 @@ workflows:
           requires:
             - test
       - build_oracle:
+          requires:
+            - test
+          filters:
+            branches:
+              only:
+                - CAT-932
+      - build_sftp:
           requires:
             - test
           filters:
